In [3]:
import numpy as np

# Create a sample matrix
a=np.array([[3, 2, 2],[2, 3, -2]])

#svd
u,s,tm = np.linalg.svd(a)


S_matrix = np.zeros((u.shape[1], tm.shape[0]))
np.fill_diagonal(S_matrix, S)

print("U matrix: ",u)
print("Singular values: ",s)
print("transpose matrix: ",tm)
print("Reconstructed matrix: ", np.dot(u, np.dot(S_matrix, tm)))


U matrix:  [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular values:  [5. 3.]
transpose matrix:  [[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]
Reconstructed matrix:  [[ 3.  2.  2.]
 [ 2.  3. -2.]]
